#@ crd_names = [
#@   "clusters.cluster.x-k8s.io",
#@   "machinedeployments.cluster.x-k8s.io",
#@   "machinehealthchecks.cluster.x-k8s.io",
#@   "machines.cluster.x-k8s.io",
#@   "machinesets.cluster.x-k8s.io"
#@ ]

#@ def crd_named(name):
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ name
#@ end
