#@ load("@ytt:data", "data"); d=data.values
#@ load("@ytt:overlay", "overlay")

#@ crd_names = [
#@   "clusters.cluster.x-k8s.io",
#@   "machinedeployments.cluster.x-k8s.io",
#@   "machinehealthchecks.cluster.x-k8s.io",
#@   "machines.cluster.x-k8s.io",
#@   "machinesets.cluster.x-k8s.io"
#@ ]

#@ def crd_named(name):
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: #@ name
#@ end

#@ for name in crd_names:
#@overlay/match by=overlay.subset(crd_named(name))
---
spec:
  #@overlay/match missing_ok=True
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1", "v1beta1"]
      clientConfig:
        caBundle: Cg==
        service:
          namespace: #@ d.service.namespace
          name: #@ d.service.name
          path: /convert
#@ end
