#@ load("@ytt:data", "data"); d=data.values
#@ load("@ytt:overlay", "overlay")

#@ def webhook_config(kind, name):
apiVersion: admissionregistration.k8s.io/v1
kind: #@ kind + "WebhookConfiguration"
metadata:
  name: #@ name
#@ end

#@ mutating_webhook_config = overlay.subset(webhook_config(kind="Mutating", name="mutating-webhook-configuration"))
#@ validating_webhook_config = overlay.subset(webhook_config(kind="Validating", name="validating-webhook-configuration"))

#@overlay/match by=overlay.or_op(mutating_webhook_config, validating_webhook_config), expects=2
#@overlay/match-child-defaults missing_ok=True
---
metadata:
  annotations:
    cert-manager.io/inject-ca-from: #@ d.certificate.namespace + "/" + d.certificate.name

